### ISSUE TITLE
Error con el paso a producción

### ISSUE THREAD

**Issue by vtellez** [eusonlito/redsys-TPV#10]
Buenas tardes,

en primer lugar agradecerte el trabajo, la verdad es que es un gustazo utilizar el paquete.

Estaba realizando pruebas de integración con laravel 5.1 y redsys, y en el entorno de pruebas facilitado por el banco todo estupendo.

El problema viene cuando cambio a la URL en producción, donde recibo un código de error como este:

SIS0042 => “La firma enviada no es correcta”,

No entiendo bien porqué ya que estoy usando la key en sha256 facilitada por el banco.. ¿Estoy olvidando algo?

**Comment by eusonlito** [comment]
Es extraño ya que el código es exactamente el mismo, sólo cambia la URL de destino de la petición (y lógicamente debes usar la clave final SHA256).

Yo tengo varios proyectos con laravel y la librería y sin ningún problema.

Te recomiendo consultar con tu banco el lunes para saber si está llegando la clave de firma correcta.

**Comment by vtellez** [comment]
Gracias por tu respuesta.

La verdad es que no entiendo nada. Si utilizo la misma key en preproducción puedo usarla sin problemas.

¿Debo añadir o modificar esa key para usarla en producción de alguna forma?

**Comment by eusonlito** [comment]
Las claves de preproducción y producción son diferentes. La de preproducción es genérica y la de producción es la final y diferente para cada cliente.

**Comment by vtellez** [comment]
Vale, acabo de darme cuenta.

Parece que hay que solicitar la key para producción por correo.

Muchísimas gracias por tu atención.

Un saludo,
