### ISSUE TITLE
Error signatura en pago diferido

### ISSUE THREAD

**Issue by joboca** [eusonlito/redsys-TPV#12]
Hola @eusonlito ,

Primero gracias por este gran paquete para Redsys.

Para mi funciona todo menos la signatura de vuelta en pago en diferido.

El pago inicial se ejecuta perfectamente:

<pre>$config = array(
        'Environment' => $url_tpv, // Puedes indicar test o real
        'MerchantCode' => $this->params->get('redsys_merchantcode'),
        'Key' => $claveModuloAdmin,
        'Terminal' => $this->params->get('redsys_terminal', 1),
        'TransactionType' => $args['transaction_type'],
        'Currency' => $this->params->get('redsys_currency', 978),
        'MerchantName' => $this->params->get('redsys_merchantname'),
        'Titular' => 'Mi Comercio',
        'ConsumerLanguage' => '001',
        'SignatureVersion' => 'HMAC_SHA256_V1'
);</pre>

Confirmación de pago:

<pre># Cargamos la clase con los parámetros base
        
$TPV = new Redsys\Tpv\Tpv($config);
        
# Indicamos los campos para la confirmación del pago
        
$TPV->sendXml(array(
        'TransactionType' => $args['transaction_type'], // Código para la Confirmación del cargo
        'MerchantURL' =>  $args['notify_url'], // 'http://dominio.com/direccion-control-pago-xml', // $args['notify_url'], // A esta URL enviará el banco la confirmación del cobro
        'Amount' => $args['amount'], // La cantidad final a cobrar
        'Order' => strval($args['order_id']), // El número de pedido, que debe existir en el sistema bancario a través de una autorización previa
        'MerchantData' => 'Televisor de 250 pulgadas'
));</pre>

Recepción de pago:

<pre># Cargamos la clase con los parámetros base

$TPV = new Redsys\Tpv\Tpv($config);

# Realizamos la comprobación de la transacción

try {
    $datos = $TPV->checkTransactionXml($_POST);
} catch (Exception $e) {
    die(file_put_contents(__DIR__.'/logs/errores-tpv.log', $e->getMessage(), FILE_APPEND));
}</pre>

Como digo el pago funciona pero en la recepción falla la signatura devolviendo el siguiente error:

Error: Signature not valid (FkJNj33vFPQXTcBDRTYAFgAhcPenJgdDCsFx5ZDcjbs= != JlpFNR7cr+geJz9Y0sn/2/tV/DN1kS++PxXumEBdq+o=)

No encuentro el motivo por que no coinciden las signaturas, te agradeceria si pudieras ayudarme a resolver el problema, muchas gracias.

**Comment by eusonlito** [comment]
Ok, lo revisaré.

Mientras puedes hacer pruebas del pago en diferido con el siguiente código:

``` php
try {
    $datos = $Redsys->checkTransactionXml($_POST);
} catch (Exception $e) {
    if (stristr($e->getMessage(), 'Signature') === false) {
        die(file_put_contents(__DIR__.'/logs/errores-tpv.log', $e->getMessage(), FILE_APPEND));
    }

    $datos = $Redsys->getTransactionParameters($_POST);
    $datos = $Redsys->xmlString2array($datos['datos']);
}
```

Saludos!

**Comment by joboca** [comment]
Gracias por la rapidez, aunque no resuelva el problema, el error viene en el cálculo de la signatura.

Espero puedas resolverlo pronto, para mi significaría mucho y si puedo contribuir con alguna ayuda (efectivo, etc.) cuenta conmigo.

**Comment by eusonlito** [comment]
Hola, he estado analizando bastante el código, por eso he tardado :)

He lanzado una versión en master y develop que en funciona correctamente en mis entornos.

Si puedes hacer la prueba, y verificas que funciona sacaré una release con esta actualización.

Saludos.

**Comment by joboca** [comment]
Hola @eusonlito he visto la modificación y has dado en el clavo.
Funciona perfectamente!!
Como te comente tengo que probar pagos por referencia pero todavía no tengo activada esta opción y se tendrá que añadir alguna línea para su funcionamiento, ya te diré como funciona.
Gracias, por este gran paquete :)

**Comment by eusonlito** [comment]
Vale, esa parte de pagos por referencia no he probado nada y puede ser que no funcione ya que la documentación es diferente: https://canales.redsys.es/canales/ayuda/documentacion/Manual%20integracion%20para%20conexion%20por%20Web%20Service.pdf

Cierro y abrimos uno nuevo con lo nuevo.
