### ISSUE TITLE
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by joboca** [eusonlito/redsys-TPV#13]
Hola @eusonlito ,

Depende del servidor pero mejor te comento, tengo este error con un servidor compartido y tengo que modificar la línea 52 de Curl.php

Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an 
open_basedir is set in /var/www/vhosts/midominio.com/httpdocs/directorio/libraries/vendor/redsys/tpv/src/Redsys/Tpv/Curl.php on line 52

Línea 52: curl_setopt($this->connect, CURLOPT_FOLLOWLOCATION, true);

La modifico por esta:
if (ini_get('open_basedir') == '' && strtolower(ini_get('safe_mode')) == 'off') {
        curl_setopt($this->connect, CURLOPT_FOLLOWLOCATION, true);
} else {
    curl_setopt($this->connect, CURLOPT_FOLLOWLOCATION, false);
}

Este error es común y creo que es la solución para algunos, si puedes añadir en nuevas actualizaciones, gracias

**Comment by eusonlito** [comment]
Listo, gracias :+1:
