### ISSUE TITLE
No se pueden añadir campos opcionales

### ISSUE THREAD

**Issue by xjrcode** [eusonlito/redsys-TPV#15]
Hola,

He probado de añadir campos como PAN, EXPIRYDATE, CVV2 de dos formas y no funciona:

- En el array de sendXML
- Con la función setOption

¿Hay alguna manera de añadirlos?

Gracias

**Comment by eusonlito** [comment]
Voy a revisar la documentación e intentaré añadir hoy todos los campos opcionales permitidos :)

**Comment by eusonlito** [comment]
En el branch de `develop` tienes una versión igual que `master` pero que recoge todos los valores remitidos al método `sendXml` y que son añadidos al XML.

Si lo pruebas y me comentas si funciona lo paso a release.

Saludos!

**Comment by eusonlito** [comment]
Merged.
