### ISSUE TITLE
¿Pueden hacerse cobros mensuales con la api de redsys?

### ISSUE THREAD

**Issue by zaqueoae** [eusonlito/redsys-TPV#17]
Hola,

No se si debería escribir aquí, pero quería saber si redsys permite los cobros mensuales mediante el tpv. Y en segundo lugar me gustaría saber si con este módulo se podría gestionar.

Mil gracias por vuestro trabajo.

**Comment by eusonlito** [comment]
Nunca he probado, pero según la documentación sí se puede.

En cualquier caso puede ser que el API inicialmente no lo permita, pero si eres desarrollador y te encuentras con limitaciones concretas en la implementación intentaré solucionarlo.

**Comment by ormedo** [comment]
Me acabas de salvar la vida, por que el puto departamento de movilidad de redsys no me responde para integrar sus pagos en una App, al menos con tu script me has ahorrado el tiempo de desarrollarlo desde cero y poder abrir un webview donde el usuario hacer el pago.

THANKS!

**Comment by JoomBall** [comment]
Con esta librería puedes hacer recurrentes.

1. Hay que activar Redsys por referencias, pedir en tu sucursal.
2. El primer pago te devuelve un identificador y caducidad tarjeta del cliente.
3. Se hace un cron o un botón para hacer un cobro pasando el identificador que previamente se a guardado en BD, esta librería lo hace en **diferido** (solo he visto otra por soap, esta por curl).

Hay un inconveniente: Cuando se caduca la tarjeta hay que volver hacer un pago inicial para crear un nuevo identificador.

Mil gracias @eusonlito
