### ISSUE TITLE
PHP 7.1 Error float json_encode()

### ISSUE THREAD

**Issue by albertnavas** [eusonlito/redsys-TPV#19]
Si por ejemplo se le pasa un amount "9,95", la función getFormHiddens() que usa la función json_encode() produce que en vez de devolver "995" devuelva "994.9999999999999"
Es un problema de la nueva versión de PHP y los cambios que han hecho en float. Pero igual de alguna forma se puede prevenir este error desde la librería de redsys y no tener que tocar la el archivo php.ini

https://stackoverflow.com/questions/42981409/php7-1-json-encode-float-issue

**Comment by eusonlito** [comment]
Interesante... no me ha pasado en ningún otro proyecto, aunque ahora estoy desarrollando en PHP 7.2

Lo miraré con calma :)

**Comment by eusonlito** [comment]
Vale, según veo eso depende de la definición de `serialize_precision` que por defecto es `-1`. Si este valor se cambia, el json se adaptará a la precisión indicada.

Puedes ver tu configuración actual con:

```
$> php -i | grep -i serialize_precision
```

**Comment by albertnavas** [comment]
Si, yo ya lo configure a 14 para que funcionara, pero si alguien actualiza PHP y no se da cuenta puede ser bastante malo. PHP debería dejar ese valor como estaba antes por defecto. Gracias mirarlo!!!

**Comment by eusonlito** [comment]
Deberías mantener el valor por defecto, que es `-1`.

Ten en cuenta que las actualizaciones de los paquetes de PHP mantienen siempre la configuración que tengas en ese momento, con lo cual no habría ningún problema con esto.
