### ISSUE TITLE
Error al recibir respuesta en devoluciones

### ISSUE THREAD

**Issue by adriangoca** [eusonlito/redsys-TPV#20]
En la clase TPV, en la función checkTransactionResponse() en la línea 373 ¿es probable que falte castear la variable response en la última validación? El código response 900 es para autorizar devoluciones, recibimos como variable response un string "0900".

**Comment by eusonlito** [comment]
Sí, efectivamente, puede ser que falte un cast en una de las comprobaciones.

Subo un cambio y lo validais.

Es raro, ya que yo también lo uso para preautorizaciones sin problema...

**Comment by adriangoca** [comment]
Perfecto, ya no tenemos problemas.

Muchas gracias.
