### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by wapcrazut** [eusonlito/redsys-TPV#21]
Hello, 

I'm having an issue when I try to get an error status code. When the user rejects the payment is redirected to the KO URL but in Symfony 3.4 is generating a Symfony exception.

> Response code is Transaction Denied 9915: PAGO CANCELADO

The  `checkTransactionResponse($data, $prefix)` function is throwing an exception when I use `checkTransaction()` for getting the status of transaction, due this I can't handle my own exceptions.

I'm using the example code, but It does not reach the exception catch, this is my code :

```
        $TPV = new Tpv($config);
        try {
            $data = $TPV->checkTransaction($_GET);
            $success = true;
            $message = '';
        } catch (Exception $e) {
            $data = $TPV->getTransactionParameters($_GET);
            $success = false;
            $message = $e->getMessage();
        }
```

Is there any way to get the Exception response code on the catch? or I'm using an incorrect method?

Thanks.

**Comment by eusonlito** [comment]
Do you want the `9915` errror code and `PAGO CANCELADO` error message in different variables?

**Comment by wapcrazut** [comment]
Perdona, no sabía que hablas Español. 

Lo que sucede es que al hacer la verificación del pago con `checkTransaction()` he notado que dentro de esta función existe una llamada a `checkTransactionResponse()` y esta valida que el response no tenga algún error. Pero, cuando tiene alguno lo que hace es arrojar una excepción y esto me genera la típica pantalla roja de Symfony.  El problema en concreto es que el `catch` del `Try ` del código de ejemplo nunca termina "activándose" ya que la excepción se genera mucho antes. Lo que me gustaría es poder tomar esa excepción en el catch  y mandar el response a una vista.

¿Es posible lo que quiero hacer? ¿hay que hacer modificaciones al Tpv.php? ¿O el método que estoy utilizando no es el adecuado?

Gracias

**Comment by eusonlito** [comment]
Claro, pero ese código es correcto, lo único que igual tienes que hacer un `use Exception` previamente en la cabecera del controlador/servicio para poder usar el `Exception` del catch.

Precisamente dado que estás usando un try/catch nunca debería lanzarte la excepción en Symfony dado que está siendo capturada.

Puede ser que el error sea por otra cosa?

Si pegas el error completo lo podremos revisar.

**Comment by wapcrazut** [comment]
Ha sido un error de novato, eso era lo que me faltaba. No estaba incluyendo el `use Exception`.
Ahora soy capaz de obtener los detalles de la excepción. 

Gracias por tu tiempo.
