### ISSUE TITLE
Problema con parámetros opcionales y faltantes

### ISSUE THREAD

**Issue by 4170R** [eusonlito/redsys-TPV#23]
Buenas eusonlito!

Primero de todo gracias por tu aportación, me ha servido de mucha ayuda en mi proyecto.
Ahora bien, tengo dos propuestas/peticiones que hacerte (no son muy complicadas tranqui jeje):

La primera:
Has puesto el campo "Titular" como obligatorio cuando no lo es, y esto puede generar problemas en un futuro. Por ejemplo en mi App no sabemos está información porque no se la pedimos al usuario y en cambio me obliga a rellenarla con cualquier cosa. ¿Podrías cambiarlo al array de campos opcionales?

La segunda:
Faltan unos cuantos parámetros más en el formulario de envío al TPV que ahora mismo no se pueden pasar (como por ejemplo Ds_Merchant_Identifier, Ds_Merchant_DirectPayment, etc...), de los cuales al menos yo necesito algunos. ¿No podrías hacer que el construct de la clase TPV recogiese cualquier parámetro entrado en el array de opciones en lugar de solo quedarte con los definidos en dicha clase? Sería relativamente sencillo hacer esto y ampliaría mucho las posibilidades de este gran trabajo que has hecho.

Muchas gracias de antemano y espero tu respuesta.

Aitor.

**Comment by eusonlito** [comment]
Cambios aplicados en `develop` para su validación

1. Listo, se ha pasado a parámetros opcionales.
2. El método `setFormHiddens` permitiría cualquier parámetro adicional a los definidos en required y optional. Debería funcionarte: https://github.com/eusonlito/redsys-TPV/blob/67b6713a5a194f0851a0d07ea2e7999e73afa6e4/src/Redsys/Tpv/Tpv.php#L130

**Comment by 4170R** [comment]
Una vez más me quito el sombrero.
Por cierto, ¿sabes cuando pasarás los cambios a la master? Para tenerlo en cuenta.
Muchas gracias de nuevo!!

**Comment by eusonlito** [comment]
En cuanto puedas validar que estos cambios de aquí funcionan, lo paso a master :)

**Comment by 4170R** [comment]
Esto todo OK! Funciona de lujo! Por mi tienes vía libre jaja
Muchas gracias!

**Comment by eusonlito** [comment]
Perfect! en cuanto validemos el `getAmount` lo mergeo a master y saco release.
