### ISSUE TITLE
Problema con parámetro Amount

### ISSUE THREAD

**Issue by 4170R** [eusonlito/redsys-TPV#24]
Buenas de nuevo eusonlito!

Me he encontrado otro problema, este un poco más grave (pero también de fácil solución).

Dentro de los parámetros del formulario, no sé exactamente por qué, pero si por ejemplo le paso "Amount" = '70,10', al ir a la pasarela de pago me da un error SIS00019 (Que indica que el formato Amount no es correcto).

He visto que la función getAmount() de esta clase TPV es diferente que la que tienes en Ceca (de hecho es más enrebesada y no sé por qué). En cambio debería ser la misma, ya que para este campo los dos TPVs funcionan igual. De hecho, he probado a sustituir dicha función por la de Ceca y se soluciona el problema.

Si pudieses cambiar esto también te lo agradecería, ya que de momento así no puedo usar tu librería.

Muchas gracias de nuevo y disculpa las molestias!

Aitor.

**Comment by eusonlito** [comment]
Hola! podrías capturar los datos que se están enviado por POST a Redsys, para ver que valor genera de Amount para esa cantidad?

**Comment by 4170R** [comment]
Si sin problema, en Amount le paso un (string) "70,10", la clase lo traduce a un (float) 7010 y los datos que se pasan por POST es el parámetro Ds_MerchantParameters pero está encriptado con la key, así que no sirve de mucho. Yo creo que el problema viene a que lo traduce a un float cuando debería ser un string (o como mucho un int). Pero ya te digo que con la función getAmount() que tienes en la librería Ceca funciona sin problemas.

Gracias por tu rápida respuesta!

**Comment by eusonlito** [comment]
Pero `7010` es correcto, es lo que espera Redsys:

> `Ds_Amount` **Obligatorio** Para Euros las dos últimas posiciones se consideran decimales, salvo en el caso de los Yenes que no tienen.

https://canales.redsys.es/canales/ayuda/documentacion/Manual%20integracion%20para%20conexion%20por%20Web%20Service.pdf

**Comment by eusonlito** [comment]
Vale, veo cual puede ser el problema, puede ser que alguna actualización de PHP añada un `.0` en los valores float.

Creo que debería cambiar:
```php
return (round($amount, 2) * 100);
```
por:
```php
return (int)(round($amount, 2) * 100);
```

**Comment by eusonlito** [comment]
He subido una actualización a `develop` 81dfc88 que debería solucionar este problema.

Que raro que nadie me hubiera hecho referencia antes, ya que tiene un montón de instalaciones :)

**Comment by 4170R** [comment]
Ya, pero como la función lo convierte a float (no sé por qué) yo creo que se hace un lío luego al encriptarlo con el resto de datos. A mi por lo menos me da error.

Por suerte la solución es fácil, que es usar la misma función que utilizas en la librería de Ceca, la cual es más simple y no convierte nada a floats.

Gracias de nuevo!

**Comment by 4170R** [comment]
Ahora he visto tu otra respuesta, voy a probarlo!
Igual la gente suele usar el formato X.XX en lugar de X,XX (que es el que convierte a float) y por eso nadie se ha percatado.

Merci por responder tan rápido!

**Comment by eusonlito** [comment]
Sí, lo sé que es la misma que Ceca, pero aquí hago más comprobaciones:

1) Quitar el punto de millar en caso de que venga: 1.000,50
2) Comprobar el formato decimal: punto o coma

Hay valores que vienen de base de datos (según la codificación) de diversa manera, por eso aquí está más preparada para estos casos.

Añadiendo el (int) en la respuesta de `getAmount` ya debería ser suficiente. Si puedes probar la versión `develop` perfecto.

**Comment by 4170R** [comment]
Pues que raro, no me acaba de funcionar bien. Es decir, ahora pasándole "70,10" no da error el TPV pero me lo convierte a un 7009, lo que para el TPV son 70,09€, cuando deberían ser 70,10€.
Utilizo la versión 7.2.4 de PHP por si te sirve de ayuda.

Entiendo lo que dices en el primer condicional para comprobar los casos tipo 1.000,50, ¿pero a partir de aquí no podría ser igual que en Ceca? No entiendo por qué haces el resto diferente (lo de canviar "," por "." y pasarlo a float etc..). Disculpa, seguramente tenga su sentido eh!

Gracias!!

**Comment by eusonlito** [comment]
Vale, déjame hacer un par de pruebas, igual pasándolo a string en vez de a int.

Quiero dejarlo bien :)

**Comment by 4170R** [comment]
Si si tranqui! Es un gran trabajo este, el resto me ha ido de perlas.
Disculpa ser tan pesado eh! jaja. Te paso como me funciona a mi para que le eches un vistazo:
```
public function getAmount($amount)
    {
        if (empty($amount)) {
            return '000';
        }
        if (preg_match('/[\d]+\.[\d]+,[\d]+/', $amount)) {
            $amount = str_replace('.', '', $amount);
        }
        if (preg_match('/[\.,]/', $amount)) {
            return str_replace(array('.', ','), '', $amount);
        }
        return ($amount * 100);
    }
```

**Comment by 4170R** [comment]
Convirtiéndolo a string parece que también funciona.. XD
Ya no te molesto más jaja, espero tu respuesta!!
Échale un vistazo al otro tema que te he abierto a ver que opinas. Merci!!

**Comment by eusonlito** [comment]
Ahora sí debería estar finalmente listo

https://github.com/eusonlito/redsys-TPV/blob/0ce0796abf8188513462fc6a861b8971ee5e48fb/src/Redsys/Tpv/Tpv.php#L301-L333

También he actualizado los Tests para la validación de todas las posiblidades:

https://github.com/eusonlito/redsys-TPV/blob/0ce0796abf8188513462fc6a861b8971ee5e48fb/tests/Redsys/Tpv/TpvTest.php#L24-L52

**Comment by 4170R** [comment]
Perfecto! Eres un crack! Muchas gracias!
Y de nuevo se agradece la rápida respuesta.

**Comment by 4170R** [comment]
Buenas de nuevo!
Sigue dándome error :S, porque a pesar de los cambios al final el amount continua siendo un float.
Simplemente te faltaría parsearlo a un string antes de retornar el valor y así si que funciona.
El resto todo ok! Gracias!

**Comment by eusonlito** [comment]
Vale, ahora esá forzado a string, yo estoy con PHP 7.2.9 y no he tenido ningún problema con esto... a saber :P

https://github.com/eusonlito/redsys-TPV/blob/6307d0d963d047a540e86666fa7548f9810c333f/src/Redsys/Tpv/Tpv.php#L331-L335

**Comment by 4170R** [comment]
Perfecto ahora funciona a las mil maravillas!
Era raro, yo uso una versión de PHP 7.2.4.

Pero vaya, ahora si que si! Testeado y funcionando! Ya no te molesto más jaja
Muchas gracias!

**Comment by eusonlito** [comment]
Gracias a ti!
