### ISSUE TITLE
SIS0042 Error en el cálculo de la firma

### ISSUE THREAD

**Issue by JoomBall** [eusonlito/redsys-TPV#25]
Hola Lito,

Hace 2-3 años que no utilizo tu libreria y antes me funcionaban los pagos recurrentes por referencia. Ahora tengo un error de firma cuando utilizo $TPV->sendXml($options);

**Datos pago con petición de nueva referencia:**

```
> Array
(
    [Environment] => real
    [MerchantCode] => XXXXXXXXXX
    [Key] => MiKey
    [Terminal] => 1
    [TransactionType] => 0
    [Currency] => 978
    [MerchantName] => XXXXXXXXXX
    [Titular] => Mi Comercio
    [ConsumerLanguage] => 001
    [SignatureVersion] => HMAC_SHA256_V1
)
Array
(
    [Ds_Merchant_Currency] => 978
    [Ds_Merchant_MerchantCode] => XXXXXXXXXX
    [Ds_Merchant_Terminal] => 1
    [Ds_Merchant_Titular] => Mi Comercio
    [Ds_Merchant_TransactionType] => 0
    [Ds_Merchant_MerchantName] => XXXXXXXXXX
    [Ds_Merchant_MerchantURL] => https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&task=redsys.paymentNotify&orderid=58
    [Ds_Merchant_ConsumerLanguage] => 001
    [Ds_Merchant_UrlOK] => https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&task=redsys.paymentSuccess
    [Ds_Merchant_UrlKO] => https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&task=order.paymentCancel&orderid=58
    [Ds_Merchant_Identifier] => REQUIRED
    [Ds_Merchant_MerchantData] => Suscripción para locales
    [Ds_Merchant_Order] => XXXXXXXXXX
    [Ds_Merchant_Amount] => 500
)
```

* Hasta aquí todo correcto y me devuelve el identificador para nuevos pagos recurrentes.

**Datos pago con referencia diferido:**

```
> Array
(
    [Environment] => real
    [MerchantCode] => XXXXXXXXXX
    [Key] => MiKey
    [Terminal] => 1
    [TransactionType] => A
    [Currency] => 978
    [MerchantName] => XXXXXXXXXX
    [Titular] => Mi Comercio
    [ConsumerLanguage] => 001
    [SignatureVersion] => HMAC_SHA256_V1
)
Array
(
    [Ds_Merchant_MerchantCode] => XXXXXXXXXX
    [Ds_Merchant_MerchantURL] => https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&task=redsys.paymentRenewalNotify&orderid=54
    [Ds_Merchant_Currency] => 978
    [Ds_Merchant_Terminal] => 1
    [Ds_Merchant_Identifier] => XXXXXXXXXX
    [Ds_Merchant_DirectPayment] => 1
    [Ds_Merchant_TransactionType] => A
    [Ds_Merchant_Amount] => 500
    [Ds_Merchant_Order] => XXXXXXXXXX
    [Ds_Merchant_MerchantData] => XXXXXXXXXX
)
```

No se que a cambiado pero antes enviando estos datos me funcionaba perfectamente.
He probado modificando Ds_Merchant_TransactionType=1 pero nada.

$TPV->sendXml($options); me devuelve error SIS0042

Me cuesta entender como generas signatura y tal vez con estos datos me puedas decir donde esta el problema.

Muchas gracias crack!

**Comment by eusonlito** [comment]
Entiendo que estás usando la firma correcta SHA256.

El SIS0042 indica que la firma no es correcta normalmente porque alguno de los datos puestos en la configuración no es correcto.

**Comment by JoomBall** [comment]
Bueno si te fijas uso [SignatureVersion] => HMAC_SHA256_V1

Te he pasado todos los datos tanto del config como de options por si ves algo extraño.

Me devuelve exactamente lo siguiente:

```
> Array
(
    [CODIGO] => SIS0042
    [RECIBIDO] => Array
        (
            [REQUEST] => Array
                (
                    [DATOSENTRADA] => Array
                        (
                            [DS_VERSION] => 0.1
                            [DS_MERCHANT_MERCHANTCODE] => XXXXXXXXXX
                            [DS_MERCHANT_MERCHANTURL] => https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&task=redsys.paymentRenewalNotify&userid=963&orderid=54
                            [DS_MERCHANT_CURRENCY] => 978
                            [DS_MERCHANT_TERMINAL] => 1
                            [DS_MERCHANT_IDENTIFIER] => XXXXXXXXXX
                            [DS_MERCHANT_DIRECTPAYMENT] => 1
                            [DS_MERCHANT_TRANSACTIONTYPE] => A
                            [DS_MERCHANT_AMOUNT] => 500
                            [DS_MERCHANT_ORDER] => XXXXXXXXXX
                            [DS_MERCHANT_MERCHANTDATA] => Suscripción para locales
                        )

                    [DS_SIGNATUREVERSION] => HMAC_SHA256_V1
                    [DS_SIGNATURE] => XXXXXXXXXX
                )

        )

)
```

**Comment by eusonlito** [comment]
Has probado si en un pago normal (sin se suscripción) funciona?

**Comment by JoomBall** [comment]
Si naturalmente y funciona, me devuelve correctamente el identificador para poder realizar pagos por referencia.
Te he añadido los datos del primer pago y los datos del recurrente

**Comment by JoomBall** [comment]
Llevo todo el día y no encuentro el problema, he llamado a Redsys y me han comentado que llega la notificación pero no les llega la firma.

Tal vez con esto puedes tener mejor idea de lo que pasa, gracias Lito

**Comment by JoomBall** [comment]
Adjunto mi código

                  $config = array(
			    'Environment' => $url_tpv, // Puedes indicar test o real
			    'MerchantCode' => $this->params->get('redsys_merchantcode'),
			    'Key' => $claveModuloAdmin,
			    'Terminal' => $this->params->get('redsys_terminal', 1),
			    'TransactionType' => $args['transaction_type'],
			    'Currency' => $this->params->get('redsys_currency', 978),
			    'MerchantName' => $this->params->get('redsys_merchantname'),
			    'Titular' => 'Mi Comercio',
			    'ConsumerLanguage' => '001',
			    'SignatureVersion' => 'HMAC_SHA256_V1'
			);
			
		    $TPV = new Redsys\Tpv\Tpv($config);
		    
		    $options = array(
		        'TransactionType' => $args['transaction_type'], // Código para la Confirmación del cargo
		        'MerchantURL' =>  $args['notify_url'],
		        'Amount' => $args['amount'], // La cantidad final a cobrar
		        'Order' => strval($args['order_id']), // El número de pedido, que debe existir en el sistema bancario a través de una autorización previa
		        'MerchantData' => $args['name']
		    );
		
		    if (isset($args['identifier'])) {
		    	$options['Identifier'] = $args['identifier'];
		    	$options['DirectPayment'] = true;
		    }
		    
		    $response = $TPV->sendXml($options);

**Comment by eusonlito** [comment]
Que raro, lo estoy revisando en un proyecto que también uso esa acción y funciona correctamente, aunque yo uso `'TransactionType' => 8`.

Deberías hacer un volcado del XML generado en https://github.com/eusonlito/redsys-TPV/blob/master/src/Redsys/Tpv/Tpv.php#L184 `$this->xmlArray2string($this->setXmlValues())` para ver si incluye correctamente todos los valores necesarios.

Igual con eso sí te pueden ayudar en Redsys.

**Comment by JoomBall** [comment]
$this->xmlArray2string($this->setXmlValues()) me devuelve:

0.1337463012https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&task=redsys.paymentRenewalNotify&userid=963&orderid=XXXXXXXXXX para XXXXXXXXXX=

**Comment by JoomBall** [comment]
$this->setXmlValues() me devuelve:

```
Array
(
    [DS_Version] => 0.1
    [DS_MERCHANT_MERCHANTCODE] => XXXXXXXXXX
    [DS_MERCHANT_MERCHANTURL] => https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&task=redsys.paymentRenewalNotify&userid=963&orderid=59
    [DS_MERCHANT_CURRENCY] => 978
    [DS_MERCHANT_TERMINAL] => 1
    [DS_MERCHANT_IDENTIFIER] => XXXXXXXXXX
    [DS_MERCHANT_DIRECTPAYMENT] => 1
    [DS_MERCHANT_TRANSACTIONTYPE] => A
    [DS_MERCHANT_AMOUNT] => 500
    [DS_MERCHANT_ORDER] => XXXXXXXXXX
    [DS_MERCHANT_MERCHANTDATA] => Suscripción para locales
)
```

**Comment by eusonlito** [comment]
Lo que vale es la respuesta de `xmlArray2string` que es el método que se encarga de firmar el XML.

El resultado final (incluidos los tags XML) es el que le tendrías que enviar a Redis para que te validen el envío.

**Comment by JoomBall** [comment]
No entiendo esto es lo que se envia, que falta?

Repito esto $this->xmlArray2string($this->setXmlValues()) me devuelve:

```
<datosentrada><ds_version>0.1</ds_version><ds_merchant_merchantcode>XXXXXXXXXX</ds_merchant_merchantcode><ds_merchant_merchanturl>https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&amp;task=redsys.paymentRenewalNotify&amp;userid=963&amp;orderid=59</ds_merchant_merchanturl><ds_merchant_currency>978</ds_merchant_currency><ds_merchant_terminal>1</ds_merchant_terminal><ds_merchant_identifier>XXXXXXXXXX</ds_merchant_identifier><ds_merchant_directpayment>1</ds_merchant_directpayment><ds_merchant_transactiontype>A</ds_merchant_transactiontype><ds_merchant_amount>500</ds_merchant_amount><ds_merchant_order>XXXXXXXXXX</ds_merchant_order><ds_merchant_merchantdata>Suscripción para locales</ds_merchant_merchantdata></datosentrada>
```

**Comment by eusonlito** [comment]
Ahora formateado se ve algo :)

Pues... como mínimo:
* Los atributos XML se formatean a mayúsculas: https://github.com/eusonlito/redsys-TPV/blob/master/src/Redsys/Tpv/Tpv.php#L193
* Faltan DATOSENTRADA, REQUEST, DS_SIGNATUREVERSION y DS_SIGNATURE https://github.com/eusonlito/redsys-TPV/blob/master/src/Redsys/Tpv/Tpv.php#L199

**Comment by JoomBall** [comment]
Perdona no he copiado bien el código por segunda vez, esto es lo que devuelve $this->xmlArray2string($this->setXmlValues()) pero si el error viene de que esta en minusculas no entiendo porque todo se convierte en minusculas. provaré a ver que puedo hacer pero si tienes una idea...

```xml
<!--?xml version="1.0"?-->
<request>
    <datosentrada>
        <ds_version>0.1</ds_version>
        <ds_merchant_merchantcode>XXXXXXXXXX</ds_merchant_merchantcode>
        <ds_merchant_merchanturl>https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&amp;task=redsys.paymentRenewalNotify&amp;userid=963&amp;orderid=59</ds_merchant_merchanturl>
        <ds_merchant_currency>978</ds_merchant_currency>
        <ds_merchant_terminal>1</ds_merchant_terminal>
        <ds_merchant_identifier>XXXXXXXXXX</ds_merchant_identifier>
        <ds_merchant_directpayment>1</ds_merchant_directpayment>
        <ds_merchant_transactiontype>A</ds_merchant_transactiontype>
        <ds_merchant_amount>500</ds_merchant_amount>
        <ds_merchant_order>XXXXXXXXXX</ds_merchant_order>
        <ds_merchant_merchantdata>Suscripción para locales</ds_merchant_merchantdata>
    </datosentrada>
    <ds_signatureversion>HMAC_SHA256_V1</ds_signatureversion>
    <ds_signature>XXXXXXXXXX/XXXXXXXXXX=</ds_signature>
</request>
```

**Comment by JoomBall** [comment]
Esto crea en mayúsculas $this->setXmlValues() pero luego el xml esta en minusculas

**Comment by JoomBall** [comment]
Bueno en el código fuente esta correctamente en mayúsculas, no encuentro problema.

```
<?xml version="1.0"?>
<REQUEST><DATOSENTRADA><DS_VERSION>0.1</DS_VERSION><DS_MERCHANT_MERCHANTCODE>XXXXXXXXXX</DS_MERCHANT_MERCHANTCODE><DS_MERCHANT_MERCHANTURL>https://www.XXXXXXXXXX.net/index.php?option=com_jbevents&amp;task=redsys.paymentRenewalNotify&amp;userid=963&amp;orderid=59</DS_MERCHANT_MERCHANTURL><DS_MERCHANT_CURRENCY>978</DS_MERCHANT_CURRENCY><DS_MERCHANT_TERMINAL>1</DS_MERCHANT_TERMINAL><DS_MERCHANT_IDENTIFIER>XXXXXXXXXX</DS_MERCHANT_IDENTIFIER><DS_MERCHANT_DIRECTPAYMENT>1</DS_MERCHANT_DIRECTPAYMENT><DS_MERCHANT_TRANSACTIONTYPE>A</DS_MERCHANT_TRANSACTIONTYPE><DS_MERCHANT_AMOUNT>500</DS_MERCHANT_AMOUNT><DS_MERCHANT_ORDER>XXXXXXXXXX</DS_MERCHANT_ORDER><DS_MERCHANT_MERCHANTDATA>Suscripci&#xF3;n para locales</DS_MERCHANT_MERCHANTDATA></DATOSENTRADA><DS_SIGNATUREVERSION>HMAC_SHA256_V1</DS_SIGNATUREVERSION><DS_SIGNATURE>XXXXXXXXXX+XXXXXXXXXX=</DS_SIGNATURE></REQUEST>
```

**Comment by eusonlito** [comment]
Te he actualizado tu comentario. Envíale eso mismo a Redsys para que te validen el XML junto con tu clave.

**Comment by JoomBall** [comment]
Hola Lito,

Comentar que ya funciona, solo quite una oción 'MerchantData' pero no creo que fuera esta la solución. Creo que el problema es lo de siempre, al hacer más de 3 pruebas Redsýs por seguridad te da un error y hay que esperar con paciéncia 24/48 horas para volver hacer pruebas. Uno no puede fiar-se del significado de los errores.

Tu código funciona perfecto!!! :)

**Comment by eusonlito** [comment]
Perfecto!

Voy editar tus comentarios para quitar toda referencia a tu configuración.

Saludos!
