### ISSUE TITLE
Campos requeridos y opcionales

### ISSUE THREAD

**Issue by 4170R** [eusonlito/redsys-TPV#26]
Buenas eusonlito!

Estamos utilizando tu trabajo en nuestro proyecto y la verdad que va de lujo. Solo me estoy encontrando un pequeño problema que ya apareció alguna vez en el pasado. El tema es que los parámetros que tienes configurados como "requeridos" no se corresponden 100% con lo descrito aquí: [https://pagosonline.redsys.es/parametros-entrada-salida.html](https://pagosonline.redsys.es/parametros-entrada-salida.html).

Por ejemplo, los campos **ConsumerLanguage** y **MerchantName** los tienes puestos como requeridos cuando son opcionales y en nuestro caso concreto esto nos perjudica, porque a veces no sabemos esta info y nos obliga a poner cualquier cosa.

¿Podrías revisar y actualizar esta lista de parámetros?

¡Muchas gracias de antemano y de nuevo felicitaciones por tu trabajo!

**Comment by eusonlito** [comment]
Okey, estos días le echo un vistazo :)

**Comment by eusonlito** [comment]
@4170R lo he aplicado en el branch `develop` si puedes probarlo, perfecto.

**Comment by 4170R** [comment]
Perfecto ahora si! Probado y funcionando.

**Comment by eusonlito** [comment]
Release lanzada.

Gracias!
