### ISSUE TITLE
Campo merchantUrl opcional

### ISSUE THREAD

**Issue by fxfr** [eusonlito/redsys-TPV#27]
¡Hola!
Estamos intentando implementar el **TpvInsite**, vamos avanzando poco a poco. Nos hemos dado cuenta de que en la clase Tpv tenemos el parámetro **MerchantUrl** como opcional pero al calcular la signatura es un parámetro obligatorio. En el TpvInsite no tenemos que introducir este parámetro.

Muchas gracias por el trabajo.
Saludos

**Comment by chiqui3d** [comment]
Has podido arreglarlo?

**Comment by eusonlito** [comment]
Lo siento! no había visto este issue. Y si lo configuras con un string vacío?

**Comment by fxfr** [comment]
El problema de mandarlo como string vacío es que entonces se manda el parámetro codificado en el MerchantParameters y Redsys manda a esa url la respuesta (cosa que en el tpv insite no hace falta). Entonces Redsys detecta que no le devuelve un 200 su llamada y pone en el tpv que ha fallado la conexión al enviar la respuesta.

**Comment by eusonlito** [comment]
Vale, entonces igual lo mejor es que el no falle con los valores de configuración opcionales. Lo reviso.

**Comment by fxfr** [comment]
Ok! gracias!

**Comment by fxfr** [comment]
¡Hola!

Al enviar por curl una petición de pago a Redsys, en el mismo curl ya tenemos la respuesta y la podemos tratar para guardar que el pago se ha realizado correctamente o no. Al tener lleno el campo merchantUrl, Redsys nos manda la respuesta a la dirección que le pongamos en merchantUrl. Por lo tanto, recibimos dos veces la respuesta por parte de Redsys.

Entiendo que nos pasa a todos y en el caso que no mandemos el parámetro merchantUrl no nos mandará la segunda respuesta.

**Comment by MaruanBO** [comment]
> ¡Hola!
> 
> Al enviar por curl una petición de pago a Redsys, en el mismo curl ya tenemos la respuesta y la podemos tratar para guardar que el pago se ha realizado correctamente o no. Al tener lleno el campo merchantUrl, Redsys nos manda la respuesta a la dirección que le pongamos en merchantUrl. Por lo tanto, recibimos dos veces la respuesta por parte de Redsys.
> 
> Entiendo que nos pasa a todos y en el caso que no mandemos el parámetro merchantUrl no nos mandará la segunda respuesta.

No deberías usar CURL para tratar el post que te envia Redsys... tratalo mediante la URL notificación configurandola en el portal de administración que os han dado desde el banco.
