### ISSUE TITLE
Problema con MerchanData o ProductDescription

### ISSUE THREAD

**Issue by Jonas21** [eusonlito/redsys-TPV#29]
Hola,

Si le envio al parametro 'setFormHiddens' el array con MerchanData o ProductDescription y una de ellas dos contiene un símbolo guardado, salta un error en redsys, como por ejemplo:
Concepto 50% de descuento.

El array con los datos sería este:
$array_input_hiddens = [
"Amount" =>  "1180.00",
"MerchantData" =>  "50 % payment Pardo 43",
"MerchantURL" => "https://www.betajm.joxanetworks.com/tpv/payment-controller.php?idp=40",
"Order" =>  "116913061166",
"ProductDescription" =>  "50 % payment Pardo 43",
"TransactionType" =>  "0",
"UrlKO" => "https://www.betajm.joxanetworks.com/tpv/payment.php?"id=40&status=ko&token=W6lBCw518RbdPICCPg/Tfh8u9uuD3g/39crK5rF8EH4=",
UrlOK" =>  "https://www.betajm.joxanetworks.com/tpv/payment.php?id=40&status=ok&token=W6lBCw518RbdPICCPg/Tfh8u9uuD3g/39crK5rF8EH4=",
]`

El fallo solo lo da si pongo el '%', y sale este error:
![image](https://user-images.githubusercontent.com/5990792/122640281-0a1f6680-d0ff-11eb-9712-f0b74ff5e165.png)

**Comment by MaruanBO** [comment]
Prueba con **%25** (lo he probado y funciona) es la referencia a **%** en RFC3986 o puedes usar https://www.urlencoder.org/ o url_encode(%)
