### ISSUE TITLE
Nueva versión API Redsys

### ISSUE THREAD

**Issue by albertcansado** [eusonlito/redsys-TPV#6]
Hola!

Redsys ha cambiado la API y la actual dejara de estar disponible el día 23/11/2015. [Más info](https://canales.redsys.es/canales/ayuda/migracionSHA256.html).

Yo tengo bastantes webs que usan tu librería y hoy he empezado a modificarla para adaptarla a la nueva API, ahora los servidores de prueba de Redsys no funcionan y no podré terminarlo.
Pero cuando lo tenga listo te haré un Pull Request para que puedas revisar el código.

Sólo quería comentarte esto y asegurarme que no estés haciendo lo mismo y haga esto para nada :P

Hasta pronto!

**Comment by eusonlito** [comment]
Ok, perfecto, le hecharé un vistazo :+1:

**Comment by eusonlito** [comment]
Entiendo que estás siguiendo esta guía https://canales.redsys.es/canales/ayuda/documentacion/Guia%20migracion%20a%20HMAC%20SHA256%20-%20conexion%20por%20redireccion.pdf

Si te parece, prefiero realizar yo la migración que estaría lista en un máximo de una semana.

Saludos!

**Comment by albertcansado** [comment]
Si, estaba siguiendo esta guía.

Ningún problema! Si necesitas algo, aquí estamos ;)

**Comment by paumoreno** [comment]
Hola!

Me sumo a la petición, y si hace falta puedo colaborar también en la adaptación a las nuevas especificaciones.

Buen trabajo con la librería, es un gusto usarla :)

**Comment by eusonlito** [comment]
En principio ya casi está lista.

Tengo que realizar los tests contra el entorno de pruebas y revisar las peticiones a través de XML para preautorizaciones y autorizaciones, pero no queda mucho.

En cuanto lo finalice sacaré un nuevo tag con la nueva versión.

La implementación será exactamente igual que la versión anterior, con lo cual el código que utilizais en vuestra aplicación será el mismo que en la versión actual.

**Comment by eusonlito** [comment]
He creado el branch para esta feature como https://github.com/eusonlito/redsys-TPV/tree/feature/sha256

Estoy a la espera de poder habilitar la firma SHA256 en mi instalación, mientras si podeis realizar alguna prueba sería perfecto.

Por cierto, sabies si permite disponer de SHA256 para pruebas y SHA1 para real mientras no tienes el código funcionando al 100%?

**Comment by albertcansado** [comment]
Yo creo que no, que cuando solicitas el código en el panel de Redsys elijes uno o otro.

Yo quería usar el código que vienen en el ejemplo para como mínimo hacer las pruebas en el servidor de test. Y después cambiar una web a real.

Reviso código y también haré pruebas ;)

Gracias!

**Comment by paumoreno** [comment]
Hola!

He estado haciendo pruebas, y he encontrado un par de errores al comprobar los datos de la petición POST de confirmación.

La corrección está en el PR #7 .

Estaría bien indicar a los usuarios que para la nueva versión necesitan tener instalado el módulo `mcrypt` de PHP, y que se debe añadir al array de configuración para el constructor de la clase Tpv:

`'SignatureVersion' => 'HMAC_SHA256_V1'`

Gracias por el trabajo!!

**Comment by eusonlito** [comment]
Sí, en cuanto saque la nueva versión actualizaré el README para incluir los cambios necesarios.

En cualquier caso el valor de `'SignatureVersion' => 'HMAC_SHA256_V1'` ya está incluido por defecto en el fichero de configuración.

PR añadido al branch, gracias! :)

**Comment by albertcansado** [comment]
Yo ahora he realizado pruebas y sólo he encontrado una pequeña cosita.
Los datos devueltos por el servidor se encuentran codificados como una cadena URL, ejemplo:

``` php
[
    "Ds_Date" => "16%2F11%2F2015",
    "Ds_Hour" => "00%3A05",
    "Ds_MerchantData" => "Televisor+de+50+pulgadas"
]
```

Para solucionarlo es tan fácil como añadir la penúltima línea en la función `checkTransition`

``` php
if ($signature !== $postSignature) {
    throw new Exception(sprintf('Signature not valid (%s != %s)', $signature, $postSignature));
}

$data = array_map('urldecode', $data);
return array_merge($post, $data);
```

No se puede añadir antes porque si no la comprobación de la signatura da error. Os parece bien añadir esta linea? Ya que revisando el código de ejemplo de PHP me ha parecido que ellos no lo hacen.

Por mi parte creo que ya se puede la librería.

**Comment by eusonlito** [comment]
Listo, he añadido la decodificación del url en la respuesta de `checkTransaction`.

Si más usuarios podeis validar el código sería perfecto :)

**Comment by vaites** [comment]
He testado y parece correcto, el pago funciona perfectamente. 

Gracias por el trabajo!

**Comment by eusonlito** [comment]
Perfecto, estoy trabajando con la recepción del XML de confirmación de preautorización, para pagos en diferido. Los pagos directos a través de TPV debería funcionar correctamente :)

**Comment by marcosgdf** [comment]
¿Podrías hacer merge de las ramas o sacar una versión beta? Lo comento porque a los que usamos composer para la gestión de dependencias nos viene mal el que esté en una rama a parte…

**Comment by eusonlito** [comment]
Lo he pasado a `master`.

En cualquier caso, por composer podrías configurarlo como `"redsys/tpv": "dev-feature/sha256"`.

**Comment by marcosgdf** [comment]
Anda, no sabía que se podía hacer eso. Gracias por el tip y por el trabajo!
