### ISSUE TITLE
Imposibilidad de obtener parámetros de respuesta de Redsys si hay un error de transacción denegada

### ISSUE THREAD

**Issue by marcosgdf** [eusonlito/redsys-TPV#8]
Si intento realizar un pago con los siguientes datos:

PAN: 1111111111111117
Caducidad: 12/20

Redsys devuelve un error de "Tarjeta ajena al servicio", lo que la función `Tpv::checkTransaction` lo traduce en una excepción `TPV returned error code SIS0093: Tarjeta no encontrada en tabla de rangos`. El problema es que de esta manera y con el nuevo sistema ya no podemos obtener el ID del pago con el que estamos trabajando ya que los parámetros se devuelven codificados y la función de descodificar `Tpv::getTransacionParameters` es privada.

El apaño sería copiar el contenido de `Tpv::getTransactionParameters` y usarlo desde fuera de la clase pero no me parece la solución apropiada…

**Comment by eusonlito** [comment]
Hola, `getTransactionParameters` es pública (https://github.com/eusonlito/redsys-TPV/blob/stable/src/Redsys/Tpv/Tpv.php#L367).

Puedes echarle un vistazo al ejemplo del `README`, y aquí tienes una otra posible versión:

``` php
$success = false;
$error = '';

try {
    $datos = $TPV->checkTransaction($_POST);
    $success = true;
} catch (Exception $e) {
    $error = $e->getMessage();
    $datos = $TPV->getTransactionParameters($_POST);
}
```

**Comment by marcosgdf** [comment]
Debo tener una versión antigua entonces. Disculpa.
